backend:
  api:
    url:
      basepath: "" # Required field. Example: http://localhost:3000
      register:
        path: "" # Required field. Must be different from other paths. Example: /register
      login:
        path: "" # Required field. Must be different from other paths. Example: /login
      save-login-history:
        path: "" # Required field. Must be different from other paths. Example: /login-history
    sts:
      authentication-type: "" # Required field. Example: 'CLIENT_CREDENTIALS'. Valid values are: 'API_KEY', 'CLIENT_CREDENTIALS', 'NONE'
      client-credentials:
        client_id: "" # Required field
        client_secret: "" # Required field
      api_key:
        value: "" # Required field
  remote-database:
    database-type: "" # Required field. Valid values are: 'MYSQL', 'MONGO_DB', 'SQL_SERVER', 'POSTGRE_SQL'
    connection:
      url: "" # Required field
      port: "" # Required field
      ssl-enabled: "" # Required field
      username: "" # Required field
      password: "" # Required field
      database: "" # Required field
    
    tables:
      users-table: "" # Required field
      login-history-table: "" # Required field
  
  in-memory-database:
    tables:
      users-table: "" # Required field
      login-history-table: "" # Required field
  
  file:
    file-name: "" # Required field

  
  backend-system: "" # Required field. Valid values are: 'API', 'REMOTE_DATABASE', 'IN_MEMORY_DATABASE' and 'FILE'.

features:
  login-history: false # Required field. Indicates wether to save user login history